class Constants {
  static const margin = 4.0;
  static const margin8 = 8.0;
  static const margin12 = 12.0;
  static const margin16 = 16.0;
  static const margin20 = 20.0;
  static const margin24 = 24.0;
  static const margin48 = 48.0;
  static const margin56 = 56.0;
  static const margin72 = 72.0;
  static const padding = 4.0;
  static const padding8 = 8.0;
  static const padding12 = 12.0;
  static const padding16 = 16.0;
  static const padding20 = 20.0;
  static const padding24 = 24.0;
  static const padding48 = 48.0;
  static const padding56 = 56.0;
  static const padding72 = 72.0;
  static const borderWidth = 1.0;
  static const cornerRadius = 4.0; // Border radius
  static const borderRadius = 100.0;
  static const divideHeight = 1.0;
  static const elevation = 4.0;
  static const sizeIcon = 24.0;
  static const pageSize = 20;
  static const heightText = 1.5;
  static const langCountryVN = "vi_VN";
  static const langCountryEN = "en_US";
  static const avatarCardSize = 56.0;
  static const topicNotification = "all";
  static const textMaxLine = 2;
}
